### ISSUE TITLE
Build sync failed

### ISSUE THREAD

**Issue by burnix13** [rive-app/rive-android#23]
I cloned the project, but when I trying to open it building fails. I see following error:

```
Build file '/Users/igorskryl/Downloads/rive-android-master/kotlin/build.gradle' line: 45

A problem occurred evaluating project ':kotlin'.
> Cannot run program "adb": error=2, No such file or directory
```

It doesn't allow me to make a submodule. Can anybody help? Thanks!

**Comment by umberto-sonnino** [comment]
Hi @burnix13!
It looks like the shell is having trouble finding `adb`.
If you haven't installed and you're using Android Studio, [install the Android SDK Platform-Tools package](https://developer.android.com/studio/releases/platform-tools) and that'll install `adb` too. And once that's installed, add it to your PATH variable.
Hope this helps!

**Comment by burnix13** [comment]
Thanks! It helped!
