### ISSUE TITLE
Incompatible version of Kotlin

### ISSUE THREAD

**Issue by KarolMB** [rive-app/rive-android#278]
Hey.

I'm trying to add Rive to project 

 `   implementation 'app.rive:rive-android:4.0.0'`

` implementation "androidx.startup:startup-runtime:1.1.1`

But when running project I'm getting error:

`gradle/caches/transforms-3/336993e4a4f4645d4e13ae6da29dfc70/transformed/jetified-rive-android-4.0.0-api.jar!/META-INF/kotlin_release.kotlin_module: Module was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.7.1, expected version is 1.5.1.`

Project kotlin version: 
`"org.jetbrains.kotlin:kotlin-gradle-plugin:1.5.30"`

Is there any specified Kotlin version required ? Or how I can solve this ?

**Comment by RamanBhayana1409** [comment]
Were you able to resolve the issue ?
