### ISSUE TITLE
Touch events do not get passed to the state machines

### ISSUE THREAD

**Issue by dimsuz** [rive-app/rive-android#282]
### Description
I'm trying several rive animations from the community site and although `RiveAnimationView` obviously consumes touch events, they seem to never arrive to the actual scene: it continues playing "idle" animations. At the same time clicking scene on the community web site does play animations.

### Provide a Repro
1. Insert [this scene](https://rive.app/community/3783-7910-point-and-click/) into any `RiveAnimationView`
2. Try clicking on the view
3. Observe that nothing happens

#### Source `.riv`/`.rev` file
Download riv file from here:
https://rive.app/community/3783-7910-point-and-click/

### Device & Versions (please complete the following information)
- Device: Samsung S10fe
- Android SDK API Level 30
- Rive-android version: 4.2.2

**Comment by zplata** [comment]
Thanks @dimsuz ! We'll take a look to see what's going on

**Comment by HayesGordon** [comment]
This should be resolved in the latest version. Please reopen and provide sample code if that is not the case.

**Comment by CacaoRick** [comment]
Possibly related: https://github.com/rive-app/rive-react-native/issues/346

The current `rive-react-native` uses `rive-android` version 10.1.6:
```
implementation 'app.rive:rive-android:10.1.6'
```
