### ISSUE TITLE
Will the target SDK version change to 33 on Aug. 2023?

### ISSUE THREAD

**Issue by FranckSCTV** [rive-app/rive-android#289]
Hi,

On https://github.com/rive-app/rive-android : 
> Currently, this runtime library supports a minimum SDK version of 21, and the target SDK verison is 31.

On https://www.reddit.com/r/androiddev/comments/xovl15/minimum_api_requirement_for_new_apps_is_it/

> Starting August 1, 2023, new apps will have to target API level 33. Starting November 1, 2023, updates to existing apps will have to target API level 33.

So, in that regard is it safe to use Rive on Android?

Thanks!

**Comment by FranckSCTV** [comment]
@umberto-sonnino 
Thank you very much for the confirmation!

**Comment by umberto-sonnino** [comment]
Hi @FranckSCTV, the target SDK has been bumped to 33 in the newest version!
