### ISSUE TITLE
Not building or syncing android demo project

### ISSUE THREAD

**Issue by giovanileitevitor** [rive-app/rive-android#291]
### Description

Hi all, i am trying to run Android Rive demo project, but i m getting a sync error.
Task 'wrapper' not found in project ':app'.

### Provide a Repro
I am using default repo informed here and checked on Master branch.

#### Screenshots

![Screenshot](url)
<img width="1390" alt="Captura de Tela 2023-04-11 às 15 08 09" src="https://user-images.githubusercontent.com/27828713/231252511-6e661eb1-9b12-4943-a5d1-ec32d6d41d29.png">

### Device & Versions (please complete the following information)

- Device: [e.g. Android Emulator, Pixel 4a]
- SDK Level [e.g. Android SDK API Level 30]

**Comment by umberto-sonnino** [comment]
Can you give us a step-by-step repro for what you're doing? e.g. 

1. git clone
2. open android studio and select the `app` configuration
3. etc.

Also, if you're cloning the repo, you need to make sure that you init the submodules and build the libraries before being able to run the example on the emulator. If you're trying to modify the codebase, try looking at our [contributing docs](https://github.com/rive-app/rive-android/blob/master/CONTRIBUTING.md)
