### ISSUE TITLE
How to set url from java file i mean programmatically set url to RiveAnimationView? 

### ISSUE THREAD

**Issue by piyush85730** [rive-app/rive-android#304]

**Comment by HayesGordon** [comment]
Hi @piyush85730 you'll need to load the HTTP file and set the resource with `animationView.setRiveBytes`

You can find an example here: https://github.com/rive-app/rive-android/blob/master/app/src/main/java/app/rive/runtime/example/HttpActivity.kt

**Comment by HayesGordon** [comment]
Going to close this issue, but feel free to reopen. Also be sure to reach out to the team on Discord if you have implementation questions where we can help out with similar issues.

**Comment by HayesGordon** [comment]
To avoid confusion, the above is only recommended if you want to programatically update your Rive animation through code (loaded from a URL). The easiest way is to instead set the URL once off through XML - see [Add RiveAnimation to your XML layout](https://help.rive.app/runtimes/overview/android#3.-add-riveanimation-to-your-layout)

**Comment by EpariNigam** [comment]
Hey @HayesGordon any reason we are not providing a direct method for setting rive resource url like we are doing for rive resource id?
