### ISSUE TITLE
No Artboard found.

### ISSUE THREAD

**Issue by srdrakcay** [rive-app/rive-android#309]
I'm getting this error for our own animations.When I use the sample animations url from the documentation its work fine. What could be issues for the animations ?

--Here my sample code ;
```kotlin
private fun setAnimations(url: String) {
        lifecycleScope.launch {
            try {
                val bytes: ByteArray = withContext(Dispatchers.IO) {
                    URL(url).openStream().use { it.readBytes() }
                }
               Rive.init(requireContext())
                binding.animationsView.setRiveBytes(bytes, fit = Fit.FIT_HEIGHT)
                delay(5000)
                binding.animationsView.stop()
                binding.animationsView.clearAnimation()
                binding.animationsView.animation = null
                binding.animationsView.visibility = View.GONE
            } catch (e: Exception) {
                Log.e("TAG", "setAnimations: ${e.message}")
                e.printStackTrace()
            }
        }
    }
```
-- Versions;
```kotlin
    implementation 'app.rive:rive-android:1.0.2'
    implementation "androidx.startup:startup-runtime:1.1.1"
```

Thanks for it

**Comment by srdrakcay** [comment]
Thanks for your suggestion I will share the result here

**Comment by srdrakcay** [comment]
Its still not working

**Comment by umberto-sonnino** [comment]
If the Artboard's not found, it might be because you're using the wrong name. Can you share your `riv` file?

**Comment by srdrakcay** [comment]
The animations coming from the service, Can you send me your e-mail I can send you the file from there

**Comment by umberto-sonnino** [comment]
> The animations coming from the service, Can you send me your e-mail I can send you the file from there

Sure thing! You can send them at support@rive.app

**Comment by srdrakcay** [comment]
I send all animations please let me know what the issues

**Comment by srdrakcay** [comment]
Thank you ,I use that to but didnt work is it possible to make a call for it ? İf its be possible you can add me on discord "srdrakcay"

**Comment by srdrakcay** [comment]
```kotlin
vm.fetchUrl("https://devapp3.boholive.app/assets/animations/chest_animation-5000.riv")
        vm.byteLiveData.observe(viewLifecycleOwner){
            binding.animationsView.setRiveBytes(
                it,
                fit = Fit.COVER
            )
        }
 ``` 
Stil not animating

**Comment by srdrakcay** [comment]
İts a company project sorry for that its not working for me I dont know why There is no error about that
