### ISSUE TITLE
Crash on 8.7.0

### ISSUE THREAD

**Issue by MuhHarisPK** [rive-app/rive-android#311]
**Crash** 

**Log:** 
Abort message: 'JNI DETECTED ERROR IN APPLICATION: JNI FindClass called with pending exception java.lang.IndexOutOfBoundsException: Invalid class app.rive.runtime.kotlin.core.RendererType$Companion index value 117. It must be between 0 and 2 at app.rive.runtime.kotlin.core.RendererType app.rive.runtime.kotlin.core.RendererType$Companion.fromIndex(int) (RendererType.kt:12) at void app.rive.runtime.kotlin.core.FileAsset.<init>(long, int) (FileAsset.kt:4) at long app.rive.runtime.kotlin.core.File.import(byte[], int, int, long) (File.kt:-2) at void app.rive.runtime.kotlin.core.File.<init>(byte[], app.rive.runtime.kotlin.core.RendererType, app.rive.runtime.kotlin.core.FileAssetLoader) (File.kt:30) at void app.rive.runtime.kotlin.RiveAnimationView.loadFileFromResource(kotlin.jvm.functions.Function1) (RiveAnimationView.kt:403) at void app.rive.runtime.kotlin.RiveAnimationView.<init>(android.content.Context, android.util.AttributeSet) (RiveAnimationView.kt:340)

**XML**
<app.rive.runtime.kotlin.RiveAnimationView
        android:id="@+id/rive_task"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        app:riveResource="@raw/rive_file"/>

**Comment by umberto-sonnino** [comment]
Hi @MuhHarisPK, this crash has been fixed in version `9.0.10`, can you upgrade to that version?

**Comment by MuhHarisPK** [comment]
is that a stable version?

**Comment by umberto-sonnino** [comment]
> @umberto-sonnino is that a stable version?

Indeed it is! In fact, our latest stable is `9.1.0`

I'll just just close this issue for now. If you still run into it in our latest, feel free to reopen it!
