### ISSUE TITLE
Missing support for Dynamically loading rive asstes (Images, Sounds, etc). 

### ISSUE THREAD

**Issue by UnHired-Coder** [rive-app/rive-android#332]
No way to customise the experience based on user basis for my many use cases, say you want a particular image used in rive animation to be loaded from a URL.

**Comment by umberto-sonnino** [comment]
Hi @UnHired-Coder, we added support for this a few months ago, have you tried looking at Out of Band Assets? 
You can check our docs [here](https://rive.app/community/doc/loading-assets/doct4wVHGPgC) or you can jump directly to an example in this repo [here](https://github.com/rive-app/rive-android/blob/e9d13a5e81fb72cbacb078546d068ff19dcde92e/app/src/main/java/app/rive/runtime/example/AssetLoaderFragment.kt#L92)

**Comment by UnHired-Coder** [comment]
@umberto-sonnino Maybe we should link this somewhere in the explainer section as well. 
I didn't check the runtime section.
